//
// Created by Chloé Belguermi on 08/11/2017.
//

#ifndef NUMKINCH_CONSTANTS_H
#define NUMKINCH_CONSTANTS_H

enum GUIConstants
{
    NB_PLAYERS = 4,

    WINDOW_WIDTH = 1280,

    WINDOW_HEIGHT = 1024,

    BUTTON_WIDTH = 100,

    BUTTON_HEIGHT = 50,

    CHAR_CARD_WIDTH = 200,

    CHAR_CARD_HEIGHT = 320,

    CHAR_CARD_MARGIN_SIDE = (WINDOW_WIDTH - 4 * CHAR_CARD_WIDTH) / 2,

    CHAR_CARD_MARGIN_TOP = 320,

    STAT_CARD_WIDTH = 310,

    STAT_CARD_HEIGHT = 162,

    CARD_WIDTH = 50,

    CARD_HEIGHT = 80,

    CARD_MARGIN_SIDE = 100,

    CARD_MARGIN_TOP = 320,

    BIG_CARD_WIDTH = 250,

    BIG_CARD_HEIGHT = 400,

    ENTITY_IMAGE_WIDTH = 200,

    ENTITY_IMAGE_HEIGHT = 100,

    ENTITY_IMAGE_MARGIN_SIDE = (BIG_CARD_WIDTH - ENTITY_IMAGE_WIDTH) / 2,

    ENTITY_IMAGE_MARGIN_TOP = 60

};

#endif //NUMKINCH_CONSTANTS_H
